### ISSUE TITLE
 autoValue not recognizing Session.get()  (like#677 )

### ISSUE THREAD

**Issue by michelkeyaerts** [aldeed/meteor-autoform#900]
How to work with ```Session.get``` in a autovalue field ?

My schema:
```
   recipient: {
      type:String,
      autoValue:function(){
        currentAuthor = Session.get("author");
        console.log(currentAuthor);  //displays the correct value on the client side console
        return currentAuthor;   //return  an  Internal server error [500]
        }       
     },    
```
I have this error on the server side shell
```
I20150419-11:00:41.787(2)? Exception while invoking method '/messages/insert' ReferenceError: Session is not defined
I20150419-11:00:41.787(2)?     at Object.messages.attachSchema.SimpleSchema.recipient.autoValue (app/lib/collections.js:69:25)
I20150419-11:00:41.787(2)?     at Object.runAV (packages/aldeed:simple-schema/simple-schema.js:318:1)
I20150419-11:00:41.788(2)?     at packages/aldeed:simple-schema/simple-schema.js:419:1
I20150419-11:00:41.788(2)?     at Array.forEach (native)
I20150419-11:00:41.788(2)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150419-11:00:41.788(2)?     at packages/aldeed:simple-schema/simple-schema.js:418:1
I20150419-11:00:41.788(2)?     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
I20150419-11:00:41.788(2)?     at [object Object].getAutoValues (packages/aldeed:simple-schema/simple-schema.js:381:1)
I20150419-11:00:41.788(2)?     at [object Object].SimpleSchema.clean (packages/aldeed:simple-schema/simple-schema.js:778:1)
I20150419-11:00:41.788(2)?     at c.deny.insert (packages/aldeed:collection2/collection2.js:467:1)

```
Is it a way to retrieve this type of value with autoform?

**Comment by aadamsx** [comment]
Try wrapping the autoValue function in an isClient?

**Comment by michelkeyaerts** [comment]
Yes  I did. And the value is returned on the client side but not on server side:
```
 recipient: {
      type:String,
      autoValue:function(){
        if (Meteor.isClient) {currentAuthor = Session.get("author");
       console.log(currentAuthor);  //return the correct value
        return currentAuthor;    };
        }       
     },    
```

**Comment by aadamsx** [comment]
I'm probably just confused, but isn't Session.get() client side only? http://docs.meteor.com/#/full/session_get

**Comment by michelkeyaerts** [comment]
Yes, Sessions work only on the client side. However, I thought  it was possible to get it in the collection's simple schema that works on both client and server side. It seems it's not possible.
Maybe, I could put a hidden form input in my quick Form and get the value from the view on client side... but, I think it's not really clean.

**Comment by michelkeyaerts** [comment]
I changed my schema:
```   recipient: {
          type:String,    
     },    ``

And in my template:`

``` <span style="display: none">{{> afQuickField name='recipient' value =user._id}} </span>```

Where user is given by:   ``` Meteor.users.findOne({_id:Session.get("author")}); ```
It works although I don't really like this solution.

**Comment by chicoboymax** [comment]
Hi, I have a similar problem, with your solution you are not using quickform anymore ?

**Comment by chicoboymax** [comment]
I used something like this to solve the problem :+1: 

AutoForm.hooks({
  addProspectForm:{
    before: {
    insert: function(doc) {
      doc.project = Session.get('active_project');
      return doc;
    }
  }
  }
});

**Comment by michelkeyaerts** [comment]
Yes, I use quickform anymore. Thank you for answering. I had not thought of hooks. I'll try it.

**Comment by aldeed** [comment]
Using form hooks to add properties from session data is the correct way to do this, or use onSubmit to submit to a server method along with the extra session data.
