### ISSUE TITLE
Using the latest meteor devel branch (5/10/15) and I'm getting this error on startup.

### ISSUE THREAD

**Issue by jasonxeno** [aldeed/meteor-autoform#933]
Using the latest meteor devel branch (5/10/15) and I'm getting this error on startup. Any ideas?

=> Errors prevented startup:                  
   
   While building package aldeed:autoform:
   packages/spacebars-compiler/codegen.js:103:1: #each has incorrect number of arguments. Use either {{#each items}} or {{#each item in items}} form of #each. (compiling
   components/afQuickFields/afQuickFields.html)
   at [object Object]._.extend.codeGenTemplateTag (packages/spacebars-compiler/codegen.js:103:1)
   at [object Object].SpacebarsCompiler._TemplateTagReplacer.def.visitObject (packages/spacebars-compiler/compiler.js:30:1)
   at [object Object].HTML.Visitor.def.visit (packages/htmljs/visitors.js:61:1)
   at Object.SpacebarsCompiler.codeGen (packages/spacebars-compiler/compiler.js:77:1)
   at Object.SpacebarsCompiler.compile (packages/spacebars-compiler/compiler.js:13:1)
   at Object.html_scanner._handleTag (packages/compileTemplates/plugin/html_scanner.js:161:1)
   at Object.html_scanner.scan (packages/compileTemplates/plugin/html_scanner.js:105:1)
   at doHTMLScanning (packages/compileTemplates/plugin/compile-templates.js:8:1)
   at Package (packages/compileTemplates/plugin/compile-templates.js:49:1)
   
   
=> Your application has errors. Waiting for file change.

**Comment by zimme** [comment]
The code in [`afQuickFields.html`](https://github.com/aldeed/meteor-autoform/blob/master/components/afQuickFields/afQuickFields.html#L2) need updating to conform with the new syntax for `#each`, but after a quick look at the new syntax I don't see a way to send in arguments.

Maybe a bug report to MDG about it is needed?

**Comment by ryan-williams** [comment]
Hi, I'm seeing this error in my own Meteor project, did you find a way around it?

**Comment by aldeed** [comment]
I'm guessing this was a temporary issue with the Meteor development codebase
